version: "3.9"
services:
  db:
    container_name: ${DB_HOST}
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    healthcheck:
      test: "curl -f localhost:3306"
      interval: 5s
      timeout: 5s
      retries: 20
  flask:
    container_name: flask
    build:
      context: .
      dockerfile: flask.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5000:5000
  fetch:
    container_name: fetch
    build:
      context: .
      dockerfile: fetch.Dockerfile
    profiles:
      - fetch
